# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'passcraftMainScreen.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainScreen(object):
    def setupUi(self, MainScreen):
        MainScreen.setObjectName("MainScreen")
        MainScreen.resize(400, 200)
        MainScreen.setMinimumSize(QtCore.QSize(400, 200))
        MainScreen.setMaximumSize(QtCore.QSize(400, 500))
        self.centralwidget = QtWidgets.QWidget(MainScreen)
        self.centralwidget.setObjectName("centralwidget")
        self.formLayout = QtWidgets.QFormLayout(self.centralwidget)
        self.formLayout.setObjectName("formLayout")
        self.titlePassCraft = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.titlePassCraft.setFont(font)
        self.titlePassCraft.setWordWrap(False)
        self.titlePassCraft.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.titlePassCraft.setObjectName("titlePassCraft")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.titlePassCraft)
        self.checkerButton = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(18)
        self.checkerButton.setFont(font)
        self.checkerButton.setObjectName("checkerButton")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.checkerButton)
        self.generatorButton = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(18)
        self.generatorButton.setFont(font)
        self.generatorButton.setObjectName("generatorButton")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.generatorButton)
        MainScreen.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainScreen)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 400, 22))
        self.menubar.setObjectName("menubar")
        MainScreen.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainScreen)
        self.statusbar.setObjectName("statusbar")
        MainScreen.setStatusBar(self.statusbar)

        self.retranslateUi(MainScreen)
        QtCore.QMetaObject.connectSlotsByName(MainScreen)

    def retranslateUi(self, MainScreen):
        _translate = QtCore.QCoreApplication.translate
        MainScreen.setWindowTitle(_translate("MainScreen", "MainWindow"))
        self.titlePassCraft.setText(_translate("MainScreen", "PassCraft"))
        self.checkerButton.setText(_translate("MainScreen", "Password Checker"))
        self.generatorButton.setText(_translate("MainScreen", "Password Generator"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainScreen = QtWidgets.QMainWindow()
    ui = Ui_MainScreen()
    ui.setupUi(MainScreen)
    MainScreen.show()
    sys.exit(app.exec_())
