# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'passwordGenerator.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_GeneratorWindow(object):
    def setupUi(self, GeneratorWindow):
        GeneratorWindow.setObjectName("GeneratorWindow")
        GeneratorWindow.resize(400, 500)
        GeneratorWindow.setMinimumSize(QtCore.QSize(400, 500))
        GeneratorWindow.setMaximumSize(QtCore.QSize(400, 500))
        self.centralwidget = QtWidgets.QWidget(GeneratorWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.titlePasswordGenerator = QtWidgets.QLabel(self.centralwidget)
        self.titlePasswordGenerator.setGeometry(QtCore.QRect(60, 10, 291, 161))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.titlePasswordGenerator.setFont(font)
        self.titlePasswordGenerator.setWordWrap(False)
        self.titlePasswordGenerator.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.titlePasswordGenerator.setObjectName("titlePasswordGenerator")
        self.labelLength = QtWidgets.QLabel(self.centralwidget)
        self.labelLength.setGeometry(QtCore.QRect(180, 180, 47, 14))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(11)
        self.labelLength.setFont(font)
        self.labelLength.setObjectName("labelLength")
        self.displayGenerator = QtWidgets.QTextBrowser(self.centralwidget)
        self.displayGenerator.setGeometry(QtCore.QRect(70, 230, 261, 61))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.displayGenerator.setFont(font)
        self.displayGenerator.setObjectName("displayGenerator")
        self.checkUppercase = QtWidgets.QCheckBox(self.centralwidget)
        self.checkUppercase.setGeometry(QtCore.QRect(130, 350, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        self.checkUppercase.setFont(font)
        self.checkUppercase.setObjectName("checkUppercase")
        self.checkSymbols = QtWidgets.QCheckBox(self.centralwidget)
        self.checkSymbols.setGeometry(QtCore.QRect(130, 390, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        self.checkSymbols.setFont(font)
        self.checkSymbols.setObjectName("checkSymbols")
        self.lengthScrollBar = QtWidgets.QScrollBar(self.centralwidget)
        self.lengthScrollBar.setGeometry(QtCore.QRect(120, 200, 160, 16))
        self.lengthScrollBar.setMinimum(8)
        self.lengthScrollBar.setMaximum(64)
        self.lengthScrollBar.setProperty("value", 8)
        self.lengthScrollBar.setTracking(True)
        self.lengthScrollBar.setOrientation(QtCore.Qt.Horizontal)
        self.lengthScrollBar.setObjectName("lengthScrollBar")
        self.generateButton = QtWidgets.QPushButton(self.centralwidget)
        self.generateButton.setGeometry(QtCore.QRect(160, 310, 75, 23))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.generateButton.setFont(font)
        self.generateButton.setObjectName("generateButton")
        GeneratorWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(GeneratorWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 400, 22))
        self.menubar.setObjectName("menubar")
        GeneratorWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(GeneratorWindow)
        self.statusbar.setObjectName("statusbar")
        GeneratorWindow.setStatusBar(self.statusbar)

        self.retranslateUi(GeneratorWindow)
        QtCore.QMetaObject.connectSlotsByName(GeneratorWindow)

    def retranslateUi(self, GeneratorWindow):
        _translate = QtCore.QCoreApplication.translate
        GeneratorWindow.setWindowTitle(_translate("GeneratorWindow", "MainWindow"))
        self.titlePasswordGenerator.setText(_translate("GeneratorWindow", "Password Generator"))
        self.labelLength.setText(_translate("GeneratorWindow", "LENGTH"))
        self.checkUppercase.setText(_translate("GeneratorWindow", "Include Uppercase"))
        self.checkSymbols.setText(_translate("GeneratorWindow", "Include Symbols"))
        self.generateButton.setText(_translate("GeneratorWindow", "Generate"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    GeneratorWindow = QtWidgets.QMainWindow()
    ui = Ui_GeneratorWindow()
    ui.setupUi(GeneratorWindow)
    GeneratorWindow.show()
    sys.exit(app.exec_())
